version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-network
    depends_on:
      - faster-whisper-api

  faster-whisper-api:
    image: faster-whisper-asr-gpu:latest
    container_name: faster-whisper
    environment:
      - ASR_MODEL=large-v2
      - ASR_ENGINE=faster_whisper
    ports:
      - "9000:9000"
    networks:
      - monitor-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  monitor-network:
    driver: bridge
